### PR TITLE
+ resolved #12

### LINKED ISSUE #12: Suggest: Project need to support Singleton Pattern
**Is your feature request related to a problem? Please describe.**
To feat feature needs (for example, high currency needs), project need to support Singleton Pattern

### PR DESCRIPTION
**Pull request by hsiong**
+ resolved #12
+ upgrade README.md

### CODE REVIEW

**Comment by szy0syz** [comment]
@coluckily06 PTAL, thx

**Comment by coluckily06** [comment]
终于....，让我大叫三声

**Comment by coluckily06** [comment]
@LG-Brother  PTAL

**Review by coluckily06 — APPROVED** [review]
俺来了

**Pull request merged**
