### PR TITLE
optimize the code, fix some problems

### LINKED ISSUE #15: Need use `Java Varargs ` to optimize some problems
**Describe the solution you'd like**
In practice, there are many situations that do not need to fill `paramObj` param, so you need to use `Java Varargs ` to optimize this problem

### LINKED ISSUE #16: use Polymorphism to optimize `header` param
**Describe the solution you'd like**
In many situations, there is no need to fill `header` param, you need optimize this param.

### LINKED ISSUE #19: Split HttpUtil to GetHttpUtil, PostHttpUtil, PutHttpUtil, DeleteHttpUtil
**Describe the solution you'd like**
In order to use better, it is suggested to split HttpUtil to HttpGetUtil, HttpPostUtil, HttpPutUtil, HttpDeleteUtil

### LINKED ISSUE #20: Update Java Bytecode Version to 11,  to use some special Java syntax
**Describe the solution you'd like**
We should update Java Bytecode Version to 11, to fit some new features, for example,  `URLEncoder.encode(String s, Charset charset)` is not compatible with Java 8.

### PR DESCRIPTION
**Pull request by hsiong**
+ resolved #15
+ resolved #16
+ resolved #19
+ resolved #20

### CODE REVIEW

**Comment by LG-Brother** [comment]
You're awesome

**Comment by szy0syz** [comment]
LGTM

**Review by LG-Brother — COMMENTED** [review]
No problem

**Review by LG-Brother — APPROVED** [review]
nice

**Pull request merged**
